RecommendationNetw/src/RecommendationNetw/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using RecommendationNetw.Repositories;
using Microsoft.AspNet.Identity;
using RecommendationNetw.Models;
using System.Security.Claims;
using RecommendationNetw.Managers;
using Microsoft.Data.Entity;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace RecommendationNetw.Controllers
{
    public class AnswersController : Controller
    {
        private readonly QuestionManager<Question> _questionManager;
        private readonly AnswerManager<Answer> _answerManager;


        public AnswersController(QuestionManager<Question> questionManager,
            AnswerManager<Answer> answerManager)
        {
            _questionManager = questionManager;
            _answerManager = answerManager;
        }    

        public async Task<IActionResult> Index(Category category)
        {
            if (category == 0)
                return HttpNotFound();

            var haveAnswers = await _answerManager.HaveAnswersInCategory(UserId, category);

            if (haveAnswers)
                return RedirectToAction("Edit", new { Category = category });

            return RedirectToAction("Create", new { Category = category});
        }

        public async Task<IActionResult> Create(Category category)
        {
            if (category == 0)            
                return HttpNotFound();            

            var questionList = await _questionManager.FindAllWithRefAsync(x => x.Category == category).ToListAsync();

            if (questionList == null)
                return HttpNotFound();

            var model = questionList.Select(x => new Answer()
            {
                Category = category,
                Question = x,
                QuestionId = x.Id
            }).ToList();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IEnumerable<Answer> model)
        {            
            if (ModelState.IsValid)
            {                
                foreach (var item in model)
                    item.OwnerId = UserId;
                 
                var result = await _answerManager.CreateRangeAsync(model);
                TempData["opertionResult"] = (result) ? "Answers saved." : "Some Error Message";
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Edit(Category category)
        {
            if (category == 0)            
                return HttpNotFound();

            var model = await _answerManager.FindAllWithRefAsync(x => category.Equals(x.Category) && UserId.Equals(x.OwnerId)).ToListAsync();

            if (model == null)            
                return HttpNotFound();            

            ViewBag.Action = "Edit";
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IEnumerable<Answer> model)
        {
            if (ModelState.IsValid)
            {
                foreach (var item in model)
                    item.OwnerId = UserId;

                var result = await _answerManager.UpdateRangeAsync(model);
                TempData["opertionResult"] = (result) ? "Answers saved." : "Some Error Message";
            }
            return RedirectToAction("Index", "Home");
        }

        private string UserId
        {
            get { return HttpContext.User.GetUserId(); }
        }
    }
}

RecommendationNetw/src/RecommendationNetw/Controllers/ModerController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using RecommendationNetw.Models;
using RecommendationNetw.Repositories;
using RecommendationNetw.Helpers;
using RecommendationNetw.ViewModels.Recommendations;
using System.Security.Claims;
using RecommendationNetw.Managers;
using Microsoft.AspNet.Authorization;

namespace RecommendationNetw.Controllers
{
    [Authorize(Roles = "moderator")]
    public class ModerController : Controller
    {
        private  readonly RecommendationManager<Recommendation> _recomManager;
        private readonly int PageSize = 3;

        public ModerController(RecommendationManager<Recommendation> manager)
        {
            _recomManager = manager;    
        }
                
        public async Task<IActionResult> Index(int page = 1)
        {
            var items = _recomManager.FindAllAsync(x => x.IsModerated.Equals(false));            

            var model = new ListViewModel()
            {
                PagingInfo = new PagingInfo(await items.CountAsync(), page, PageSize),

                Items = await items.Skip((page - 1) * PageSize)
                    .Take(PageSize)
                    .ToListAsync(),                
            };
            return View(model);
        }         
    }
}

RecommendationNetw/src/RecommendationNetw/Controllers/RecommendationsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using RecommendationNetw.Models;
using System.Threading.Tasks;
using RecommendationNetw.Helpers;
using RecommendationNetw.ViewModels.Recommendations;
using System.Security.Claims;
using Microsoft.AspNet.Authorization;
using RecommendationNetw.Managers;
using Microsoft.Data.Entity;
using RecommendationNetw.Services;

namespace RecommendationNetw.Controllers
{
    [Authorize]
    public class RecommendationsController : Controller
    {
        private readonly RecommendationManager<Recommendation> _recomManager;
        private readonly RecommendationService<ApplicationUser,Answer,Set> _service = null;

        private readonly int PageSize = 3;

        public RecommendationsController(RecommendationManager<Recommendation> manager, RecommendationService<ApplicationUser, Answer, Set> service)
        {
            _recomManager = manager;
            _service = service;            
        }

        // GET: Recommendations
        public async Task<IActionResult> Index(int page = 1)
        {
            var userId = HttpContext.User.GetUserId();

            var items = _recomManager.FindAllAsync(x => userId.Equals(x.OwnerId));            

            var model = new ListViewModel()
            {
                PagingInfo = new PagingInfo(await items.CountAsync(), page, PageSize),

                Items = await items.Skip((page - 1) * PageSize)
                    .Take(PageSize)
                    .ToListAsync(),                
            };

            return View(model);
        }        

        // GET: Recommendations/Details/5
        public async Task<IActionResult> Details(string Id)
        {           
            if (Id == null)
            {
                return HttpNotFound();
            }
            var recommendation = await _recomManager.FindByIdAsync(Id);

            if (recommendation == null)
            {
                return HttpNotFound();
            }
            return View(recommendation);
        }

        // GET: Recommendations/Create
        public IActionResult Create()
        {
            return View(new Recommendation());
        }

        // POST: Recommendations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title, ShortDescription, Description, Category")] Recommendation model)
        {
            if (ModelState.IsValid)
            {
                model.OwnerId = HttpContext.User.GetUserId();
                var result = await _recomManager.CreateAsync(model);
                TempData["opertionResult"] = (result) ? "Recommendation saved." : "Some Error Message";
            }
            return RedirectToAction("Index");
        }
        
        // GET: Recommendations/Edit/Id
        public async Task<IActionResult> Edit(string Id)
        {
            if (Id == null)
            {
                return HttpNotFound();
            }

            var userId = HttpContext.User.GetUserId();
            var model = await _recomManager.FindByIdAsync(Id);

            if (model == null || !model.OwnerId.Equals(userId))
            {
                return HttpNotFound();
            } 
                       
            return View(model);
        }

        // POST: Recommendations/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id, Title, ShortDescription, Description, Category")] Recommendation model)
        {
            if (ModelState.IsValid)
            {
                model.OwnerId = HttpContext.User.GetUserId();
                var result = await _recomManager.UpdateAsync(model);
                TempData["opertionResult"] = (result) ? "Recommendation saved." : "Some Error Message";
            }
            return RedirectToAction("Index");
        }

        //POST: Recommendations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string Id)
        {
            var result = await _recomManager.DeleteAsync(Id);
            TempData["opertionResult"] = result ? "Recommendation deleted.": "Some Error Message";
            return RedirectToAction("Index");
        }

        //GET: Recommendations/Delete/5
        public async Task<IActionResult> Delete(string Id)
        {
            if (Id == null)
            {
                return HttpNotFound();
            }

            var userId = HttpContext.User.GetUserId();
            var model = await _recomManager.FindByIdAsync(Id);

            if (model == null || !model.OwnerId.Equals(userId))
            {
                return HttpNotFound();
            }

            return PartialView("_DeleteConfirm", model);
        }

        public async Task<IActionResult> GetRecommendations(Category category)
        {
            if (category == 0)
            {
                return HttpNotFound();
            }
           
            var recommendations2 = await _service.GetSimilarUsers2(User.GetUserId(), category);



            return View();
        }
    }
}

RecommendationNetw/src/RecommendationNetw/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - RecommendationNetw</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
        @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
    </head>
    <body>        
        <div class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">RecommendMe</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">                        
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Recommendations" asp-action="Index">My recommendations</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Get recommendations <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @foreach (var item in Enum.GetValues(typeof(Category)))
                                {
                                    <li><a asp-controller="Recommendations" asp-action="GetRecommendations" asp-route-category="@item">@item.ToString()</a></li>
                                }
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Questionary <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @foreach (var item in Enum.GetValues(typeof(Category)))
                                {
                                    <li><a asp-controller="Answers" asp-action="Index" asp-route-category="@item">@item.ToString()</a></li>
                                }
                            </ul>
                        </li>
                        
                        @if (User.IsInRole("moderator"))
                        {
                            <li><a asp-controller="Moder" asp-action="Index">Home</a></li>                            
                        }
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2016 - RecommendationNetw</p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>            
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>
        @RenderSection("scripts", required: false)
    </body>
</html>

RecommendationNetw/src/RecommendationNetw/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecommendationNetw</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/loginWindow.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/loginWindow.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body class="loginWindow">
    <div class="content">
        <div class="container">
            @RenderBody()
        </div>
    </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>
        @RenderSection("scripts", required: false)
</body>
</html>